### ISSUE TITLE
tmp file not deleted in /dev/shm

### ISSUE THREAD

**Issue by misterbh** [yoctu/yosh#49]
**Describe the bug**
/dev/shm
**To Reproduce** is full of tmp.XXXXX files that are not deleted at the end of execution

1. Go to '/dev/shm'
2. do ls -al and wait to get the result'

**Expected behavior**
no tmp.XXXX files should be visible except during execution time

**Additional context**
This bug appears in the release made the 12th march 2019

**Comment by dzove855** [comment]
Can you please provide me you're configuration Files or show me the code who is creating the tnpFile.

Normally you should use Mktemp::create to create Public tmp files instead of mktemp. 

⁣
Github: github.com/dzove855
IRC: dzove855​

**Comment by misterbh** [comment]
https://github.com/yoctu/yosh/blob/037147f59099b594fbc8be8875d18dbf77543812/lib/mktemp.sh is creating files ;-)

**Comment by dzove855** [comment]
Yes sure, but files created with this function will be removed on the end. But i will have a further look into this.

**Comment by misterbh** [comment]
Yosh::on::exit seems to be faulty and it's not deleting anything

**Comment by dzove855** [comment]
Correction pushed on branch develop, can you please retry and keep me updated?

**Comment by misterbh** [comment]
Thank you Dzove855

**Comment by lvenier** [comment]
any news ?
we need also to remove the ugly touch in build in few days :)

**Comment by dzove855** [comment]
Normally it is fixed, but i wait a confirmation from misterbh

⁣
Github: github.com/dzove855
IRC: dzove855​

**Comment by misterbh** [comment]
And I wait access to yoctu dev env in order to check, any news? ;-)

**Comment by lvenier** [comment]
you need to be bash black belt for yoctu access... 
for the moment tou can only access veb's plex server. Enjoy the movies :)

**Comment by misterbh** [comment]
Ok noted, please check if the commit solved the issue, @dzove855 then you expect a feedback from lvenier 😉

**Comment by dzove855** [comment]
Haha enjoy, there're a lot of nice movies :D

⁣
Github: github.com/dzove855
IRC: dzove855​

**Comment by lvenier** [comment]
checked and ok. you can merge to master.

**Comment by misterbh** [comment]
at the same time the films on the plex were good ;-)

**Comment by lvenier** [comment]
stay focus :)

**Comment by dzove855** [comment]
https://github.com/yoctu/yosh/pull/50

Can you please remove the delete after who is in the postinst?

**Comment by dzove855** [comment]
Merged and pushed on prod
