### ISSUE TITLE
Feature/Yosh_API_MODE

### ISSUE THREAD

**Issue by dzove855** [yoctu/yosh#7]
TODO:
    - New API Error Handler - DONE
    - Add package system in YOSH instead of only Applications - DONE
    - JSON-to-array in Post Data - X
    - Add PATCH in api mode - DONE
    - Change OPTIONS Header - X
    - Add access allow origin - DONE
    - Split Yosh - X

**Comment by lvenier** [comment]
@dzove855 : Any progress on the request ?
